[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter = "C4DUVQbRkwGLb56yWxuXBYYxmDR76GJ8t23hgvMHr6gB"
predicate_registry = "GjXtvmWihnf22Bg48srpzYrs6iGhSUvu1tzsf9L4u9Ck"

[programs.localnet]
counter = "C4DUVQbRkwGLb56yWxuXBYYxmDR76GJ8t23hgvMHr6gB"
predicate_registry = "GjXtvmWihnf22Bg48srpzYrs6iGhSUvu1tzsf9L4u9Ck"

[programs.mainnet]
counter = "DNqiXmRMXgcGaqFJAegJT4EZd7e6b3S7mTpT3EsXMDdn"
predicate_registry = "GjXtvmWihnf22Bg48srpzYrs6iGhSUvu1tzsf9L4u9Ck"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/deployment-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/{functional,security}/**/*.test.ts' --exit"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
